<?php

namespace Database\Seeders;

use App\Models\Laptop;
use Illuminate\Database\Seeder;

class LaptopSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $laptops = [
            // Gaming Laptops
            [
                'name' => 'ROG Zephyrus G16',
                'brand' => 'ASUS',
                'description' => 'High-performance gaming laptop with RTX 4090 graphics and 12th gen Intel processor. Perfect for competitive gaming and content creation.',
                'price' => 3499.99,
                'processor' => 'Intel Core i9-12900HK',
                'ram' => '32GB DDR5',
                'storage' => '1TB NVMe SSD',
                'graphics' => 'NVIDIA RTX 4090',
                'display' => '16" 4K OLED 120Hz',
                'weight' => 2.5,
                'battery_life' => '6 hours',
                'category' => 'gaming',
                'stock' => 5,
                'is_featured' => true,
            ],
            [
                'name' => 'Legion Pro 9',
                'brand' => 'Lenovo',
                'description' => 'Ultimate gaming powerhouse with advanced cooling and RGB lighting. Designed for extreme gaming performance.',
                'price' => 3299.99,
                'processor' => 'Intel Core i9-13980HX',
                'ram' => '32GB DDR5',
                'storage' => '2TB NVMe SSD',
                'graphics' => 'NVIDIA RTX 4080',
                'display' => '16" QHD+ 240Hz',
                'weight' => 2.8,
                'battery_life' => '5 hours',
                'category' => 'gaming',
                'stock' => 3,
                'is_featured' => true,
            ],
            [
                'name' => 'MSI Raider GE78',
                'brand' => 'MSI',
                'description' => 'Compact gaming laptop with powerful specs. Great for portable gaming without compromising performance.',
                'price' => 2899.99,
                'processor' => 'Intel Core i7-13700HX',
                'ram' => '24GB DDR5',
                'storage' => '1TB NVMe SSD',
                'graphics' => 'NVIDIA RTX 4070',
                'display' => '15.6" FHD 144Hz',
                'weight' => 2.6,
                'battery_life' => '4 hours',
                'category' => 'gaming',
                'stock' => 8,
                'is_featured' => false,
            ],

            // Business Laptops
            [
                'name' => 'ThinkPad X1 Extreme',
                'brand' => 'Lenovo',
                'description' => 'Professional workstation for business professionals. Excellent build quality and performance for enterprise work.',
                'price' => 2299.99,
                'processor' => 'Intel Core i7-13700H',
                'ram' => '32GB DDR4',
                'storage' => '1TB NVMe SSD',
                'graphics' => 'NVIDIA RTX 4060',
                'display' => '16" 2.5K IPS',
                'weight' => 1.9,
                'battery_life' => '8 hours',
                'category' => 'business',
                'stock' => 12,
                'is_featured' => true,
            ],
            [
                'name' => 'MacBook Pro 16"',
                'brand' => 'Apple',
                'description' => 'Premium professional laptop with M2 Max chip and stunning Retina display. Ideal for creative professionals.',
                'price' => 2499.99,
                'processor' => 'Apple M2 Max',
                'ram' => '32GB Unified Memory',
                'storage' => '1TB SSD',
                'graphics' => '12-core GPU',
                'display' => '16" Liquid Retina XDR',
                'weight' => 2.1,
                'battery_life' => '17 hours',
                'category' => 'business',
                'stock' => 7,
                'is_featured' => true,
            ],
            [
                'name' => 'Dell XPS 17',
                'brand' => 'Dell',
                'description' => 'Premium Windows laptop for professionals. Combines power and portability in a sleek design.',
                'price' => 2199.99,
                'processor' => 'Intel Core i7-13700H',
                'ram' => '16GB DDR5',
                'storage' => '512GB NVMe SSD',
                'graphics' => 'NVIDIA RTX 4070',
                'display' => '17" OLED 3.5K',
                'weight' => 2.3,
                'battery_life' => '10 hours',
                'category' => 'business',
                'stock' => 6,
                'is_featured' => false,
            ],

            // Student Laptops
            [
                'name' => 'IdeaPad 3',
                'brand' => 'Lenovo',
                'description' => 'Budget-friendly laptop perfect for students. Great performance for everyday tasks and studies.',
                'price' => 599.99,
                'processor' => 'AMD Ryzen 5 5500U',
                'ram' => '8GB DDR4',
                'storage' => '512GB NVMe SSD',
                'graphics' => 'AMD Radeon Graphics',
                'display' => '15.6" HD',
                'weight' => 1.9,
                'battery_life' => '7 hours',
                'category' => 'student',
                'stock' => 25,
                'is_featured' => true,
            ],
            [
                'name' => 'VivoBook 15',
                'brand' => 'ASUS',
                'description' => 'Affordable and reliable laptop for students. Perfect for note-taking, research, and entertainment.',
                'price' => 649.99,
                'processor' => 'AMD Ryzen 7 5700U',
                'ram' => '8GB DDR4',
                'storage' => '256GB SSD',
                'graphics' => 'AMD Radeon Graphics',
                'display' => '15.6" FHD',
                'weight' => 1.8,
                'battery_life' => '8 hours',
                'category' => 'student',
                'stock' => 20,
                'is_featured' => false,
            ],
            [
                'name' => 'Inspiron 15',
                'brand' => 'Dell',
                'description' => 'Student-friendly laptop with solid performance and great value for money.',
                'price' => 549.99,
                'processor' => 'Intel Core i5-1235U',
                'ram' => '8GB DDR4',
                'storage' => '256GB SSD',
                'graphics' => 'Intel Iris Xe',
                'display' => '15.6" FHD',
                'weight' => 1.75,
                'battery_life' => '7 hours',
                'category' => 'student',
                'stock' => 30,
                'is_featured' => false,
            ],

            // Ultrabook
            [
                'name' => 'MacBook Air M2',
                'brand' => 'Apple',
                'description' => 'Ultra-thin and lightweight with exceptional battery life. Perfect for on-the-go professionals.',
                'price' => 1299.99,
                'processor' => 'Apple M2',
                'ram' => '8GB Unified Memory',
                'storage' => '512GB SSD',
                'graphics' => '10-core GPU',
                'display' => '13.6" Liquid Retina',
                'weight' => 1.24,
                'battery_life' => '18 hours',
                'category' => 'ultrabook',
                'stock' => 10,
                'is_featured' => true,
            ],
            [
                'name' => 'ZenBook 14',
                'brand' => 'ASUS',
                'description' => 'Sleek ultrabook with premium build quality and impressive performance. Ideal for travelers.',
                'price' => 1099.99,
                'processor' => 'AMD Ryzen 7 6800H',
                'ram' => '16GB DDR4',
                'storage' => '512GB NVMe SSD',
                'graphics' => 'AMD Radeon Graphics',
                'display' => '14" OLED FHD',
                'weight' => 1.4,
                'battery_life' => '13 hours',
                'category' => 'ultrabook',
                'stock' => 8,
                'is_featured' => false,
            ],
            [
                'name' => 'XPS 13 Plus',
                'brand' => 'Dell',
                'description' => 'Ultra-portable premium ultrabook. Minimalist design with maximum performance and battery life.',
                'price' => 1199.99,
                'processor' => 'Intel Core Ultra 7',
                'ram' => '16GB DDR5',
                'storage' => '512GB NVMe SSD',
                'graphics' => 'Intel Arc Graphics',
                'display' => '13.4" OLED',
                'weight' => 1.2,
                'battery_life' => '15 hours',
                'category' => 'ultrabook',
                'stock' => 6,
                'is_featured' => false,
            ],
        ];

        foreach ($laptops as $laptop) {
            Laptop::create($laptop);
        }
    }
}
