stages:
  - deploy
  - mirror

deploy:
  stage: deploy
  tags:
    - runner-development-shell
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - |
      sudo -u www rsync -az --no-o --no-g \
        --exclude=.git \
        --exclude=.env \
        --exclude=node_modules \
        --exclude=vendor \
        --exclude=storage \
        --exclude=proxy_cache_dir \
        --exclude=.user.ini \
        ./ "$DEPLOY_DIR/"

    - sudo -u www bash -lc "
        cd '$DEPLOY_DIR' &&
        composer install --no-interaction --prefer-dist --optimize-autoloader &&
        php artisan migrate --force &&
        php artisan storage:link
      "

# ================================
# 3️⃣ Mirror code to Github (branch main)
# ================================
mirror_production_to_github:
  tags:
    - runner-development-shell
  stage: mirror
  variables:
    GIT_DEPTH: 0
  script:
    - git remote remove github || true
    - echo "Mirror code to GitHub repository => $GITHUB_USER/$GITHUB_REPO"
    - git remote add github https://oauth2:$GITHUB_TOKEN@github.com/$GITHUB_USER/$GITHUB_REPO.git

    # pastikan branch main ada
    - git fetch origin main
    - git checkout -B main origin/main

    # push ke GitHub
    - git push github main:main --force
  only:
    - main
